### ISSUE TITLE
'priority' is only available on iOS 8.0 or newer

### ISSUE THREAD

**Issue by chip** [meteor/cordova-plugin-meteor-webapp#1]
Hi, I'm currently running `METEOR@1.3-cordova-beta.5` due to some issues with **HCP** and have recently run into Xcode build errors related to **...is only available on iOS 8.0 or newer** when attempting to build against a **7.0 Deployment target**:

![ios-8 0-or-newer](https://cloud.githubusercontent.com/assets/31725/13825253/b909fce8-eb7f-11e5-8ec9-b531f6f3fde9.png)

I need to support **7.0**. Is there a workaround for this?

Thanks in advance for all of your hard work on Meteor!

**Comment by chip** [comment]
Building this for **8.0** is successful, but the app crashes immediately after opening it.

**Comment by martijnwalraven** [comment]
Closing the because iOS 7.0 is no longer supported.
