### ISSUE TITLE
startup timer starting when entering foreground

### ISSUE THREAD

**Issue by tafelito** [meteor/cordova-plugin-meteor-webapp#15]
Hi @martijnwalraven, I noticed that you made a commit on the master so you Don't restart timer when entering the foreground, is there any reason why you didn't apply this to the swift3 brunch? I'm using that for my app and I see that piece of code is causing my app to forceReload every time enter the app from the background if the version I have was previously updated. 

Thanks

**Comment by martijnwalraven** [comment]
@tafelito: The swift3 branch is outdated and should probably be removed now that is has been merged with master. The most recent released version of the plugin (1.4.1) supports Swift 3 and also includes the foreground fix you mention.

**Comment by tafelito** [comment]
Thank you @martijnwalraven, good to know, switching back to master again then

**Comment by martijnwalraven** [comment]
@tafelito: Or you could just `meteor add cordova:cordova-plugin-meteor-webapp@1.4.1`.

**Comment by tafelito** [comment]
yeah, thats what I meant!

Thanks!
