### ISSUE TITLE
Version mismatch for index page

### ISSUE THREAD

**Issue by jstoup111** [meteor/cordova-plugin-meteor-webapp#2]
Trying to understand exactly what this means. I'm getting this when I point to my production system in AWS ELB.

message: "Version mismatch for index page, expected: 158efbf027f653683e4710636e4f1f6b2ecd0d41, actual: 0893ceba7da84eaa6d4b91dfa746e26b7c9a78a

**Comment by cunneen** [comment]
+1

**Comment by micson1** [comment]
Same here, seems to be related to building the app on mac (ios/android) - and building the server-only on our ubuntu server.

**Comment by YY030913** [comment]
+1

**Comment by lorensr** [comment]
Anyone figure this out? It means that the version hash in `/index.html` (`autoupdateVersionCordova `) doesn't match the one in the manifest (`version` field in `/__cordova/manifest.json`). It should match, and normally it does. I don't know what types of problems might make them not match.

https://github.com/meteor/cordova-plugin-meteor-webapp/blob/8bbf1aefa64f424896b3fc0aaf54775f313177b5/src/ios/AssetBundleDownloader.swift#L346

**Comment by hwillson** [comment]
Hi all - can anyone confirm if this issue is still happening?

**Comment by cunneen** [comment]
I still get it on 1.6.0.
I'm also building on a mac, but I suspect most people developing cross-platform mobile apps are on a mac.

**Comment by zhang2118** [comment]
+1 on Meteor 1.6.0

**Comment by benjamn** [comment]
Please feel free to reopen this issue if the problem is still happening in Meteor 1.8. We've made a lot of changes to the way bundle versions are handled since this issue was opened, so I'm optimistic the situation has changed/improved somewhat.
