### ISSUE TITLE
iOS status bar padding missing

### ISSUE THREAD

**Issue by mikepaszkiewicz** [meteor/cordova-plugin-meteor-webapp#21]
After upgrading to 1.4, I was only able to run iOS by using this package. On the device it seeems to have trimmed off 20px or so.

**Comment by johnthepink** [comment]
@mikepaszkiewicz I posted a temporary work around over here https://github.com/meteor/meteor/issues/7988#issuecomment-259462683

**Comment by JulienMalige** [comment]
@johnthepink I'm not sure that we are talking about the same thing. StatusBarOverlaysWebView is true and working, but the padding top is not (auto)incremented by 20px.

**Comment by hwillson** [comment]
This has been fixed in recent versions of Meteor (>= 1.6.x).
