### ISSUE TITLE
GCD local web server should run in the background

### ISSUE THREAD

**Issue by awwx** [meteor/cordova-plugin-meteor-webapp#24]
In normal app startup, the app is started in the foreground, the WebAppLocalServer plugin starts the GCD local web server, the Cordova WKWebViewEngine plugin starts the web view, and the Meteor app loads from the local web server.

The GCD local web server is stopped when the application enters the background.  (See https://github.com/awwx/meteor-bg-web-bug for a reproduction).

When an app enters the background, typically iOS will suspend the app after a couple of seconds, so most applications may not notice that the local web server isn't running (the app won't be doing anything, much less making requests to the local web server, when it's suspended).

However, iOS apps can request additional running time in the background.

An iOS app can also be *started* in the background.

For example, an iOS app can request that a file be uploaded or downloaded in the background, so that the file transfer can run even if the app itself isn't running.  The app can have iOS notify the app when the file transfer completes (so that, for example, it can record that the file transfer finished or show a notification to the user).  If the app isn't running at the time the file transfer completes, iOS will start the app in the background to provide the notification.

I had [previously](https://github.com/meteor/cordova-plugin-meteor-webapp/pull/9) noted that the app version was being blacklisted when the app started in the background, and I offered a PR to not start the backlist timer.  However the *real* issue as it turns out is that Meteor is attempting to start up in the web view... but Meteor fails to load because the GCD web server isn't running at that point.

(Specifically, the CDVViewController `loadRequest:` method is called, and the WKWebViewEngine `didStartProvisionalNavigation:` method is triggered, but it never makes it to the WKWebViewEngine `didFinishNavigation:` method or to the WebAppLocalServer `pageDidLoad` method.)

If the user then brings the app into the *foreground* (for example, if they saw the notification that the file upload completed and opened the app), at that point the app is hung at the splash screen because the web view had already tried and failed to load the app.

We can tell the GCD local server to not stop in the background:

```
    let options = [
      GCDWebServerOption_Port: NSNumber(value: localServerPort as UInt),
      GCDWebServerOption_BindToLocalhost: true,
      GCDWebServerOption_AutomaticallySuspendInBackground: false]  // <-- added
    try localServer.start(options: options)
```

**Comment by awwx** [comment]
Updated: noting that Meteor apps can run in the background on iOS (previously I had the impression that the web view didn't run in the background, but it turned out that app was actually getting suspended), and so the GCD local web server should run in the background (as otherwise requests the app makes to the local web server will fail if the app happens to be running in the background).

**Comment by levinse** [comment]
@martijnwalraven any chance this could get fixed upstream soon with that PR? We have confirmed the fix works for us - ran into this issue after upgrading to 1.4.

**Comment by troyberg** [comment]
Any plan to implement this fix in the near future? This is a big issue for one of my applications.

**Comment by abernix** [comment]
Please forgive my unfamiliarity with details of the Cordova implementation; I'll try and move this along however I can (including getting it published!), however could those more familiar with this outline out any potential problems that could arise from this change (specifically that which was submitted with PR #25)?  For example, battery considerations, degraded background performance?  Is there another way that this could be solved?

The original write-up here makes sense here, but anything additional which you can provide which would make me more comfortable in merging it would be appreciated. :smile:

**Comment by awwx** [comment]
@abernix note that "run in the background" doesn't mean that the web server runs continuously on the device.

It means that when the app is in the background state, the web server doesn't refuse requests from the app.  It doesn't change when and for how long the app is run in the background.

Except for a few specific exceptions such as a map application which actually do need to run continuously in the background to provide turn-by-turn directions, iOS will normally only run apps in the background state for brief periods.  Such as allowing the app to respond to events.  iOS will run the app briefly in the background to handle the event, and then suspends it again.

So as far as I know there shouldn't be any impact on battery life.  (Even if someone did implement e.g. a map application that runs continuously in the background and Apple approved that for the app store, enabling the web server wouldn't change resource consumption: either the app as a whole is running in the background or it isn't.)

Thus the fix seems reasonable to me based on my understanding, but I'm hardly an expert on Meteor's Cordova integration, and I could have missed some other ramification.

Having the Meteor app hang if the app is started in the background is a major bug in Meteor's integration with Cordova, unique to Meteor's approach of using a web server instead of file: URL's.

If you yourself aren't familiar with Meteor's integration with Cordova, perhaps it might make sense for you to find someone at Meteor who *is*, to take a look at the situation and see if this is in fact a good solution?

**Comment by stormbkk87** [comment]
I think this issue is also related to mine. Worked fine before Meteor started using GCDWebServer. But setting the AutomaticallySuspendInBackground setting to false doesn't fix my issue. Any ideas?

[Issue 8112](https://github.com/meteor/meteor/issues/8112)

**Comment by awwx** [comment]
> I think this issue is also related to mine.

I don't think so... the bug here is that Meteor is unable to load assets (JavaScript, CSS, images) from the local web server.  If you're not unable to load assets (which would prevent your app from running at all) then I doubt you're seeing this bug.  (Which explains why setting AutomaticallySuspendInBackground didn't help with your issue).

Note that this bug isn't triggered if the app is merely suspended, or even if it's unloaded from memory and then started in the foreground.  It's only if the app is *unloaded* from memory (not just suspended) by iOS *and* then is *started* in the *background* that triggers this bug.
