### ISSUE TITLE
Hot code push failure because of assetmanager

### ISSUE THREAD

**Issue by sirpy** [meteor/cordova-plugin-meteor-webapp#26]
Hot code push seems to fail with an exception about
```
MeteorWebApp: Download failure
I20170124-17:06:12.565(2)? 01-24 15:06:11.780 32223   818 W MeteorWebApp: com.meteor.webapp.WebAppException: Non-success status code 404 for asset: /
I20170124-17:06:12.565(2)? 01-24 15:06:11.780 32223   818 W MeteorWebApp: 	at com.meteor.webapp.AssetBundleDownloader.verifyResponse(AssetBundleDownloader.java:155)
```

Debugging further this seems to stem from the automatically added asset "index.html" with url "/" in the AssetBundle constructor.
It then fails to download this asset with the above exception.
the manifest.json doesnt seem to have any entry for index.html or /,
 is this supposed to be this way?
is this is an error in generating the manifest?
is this an with meteor not serving / or /index.html correctly?
I see the index in the assets

**Comment by 16chuang** [comment]
@sirpy Did you end up resolving this issue?

**Comment by sirpy** [comment]
yes. it turned out this is a React Router SSR issue.
it tried to also route requests to __cordova and such
I had to create a fork of it and modify route handling.
https://github.com/knil-public/meteor-react-router-ssr/tree/3.1.7
