### ISSUE TITLE
SWIFT_VERSION doesn't get set the first time you run from a clean state

### ISSUE THREAD

**Issue by remmarcoux** [meteor/cordova-plugin-meteor-webapp#28]
In our attempt to automate our builds we've been encountering the "Set SWIFT_VERSION" issue on our build machines, whereas they most of the time start from a clean state.

I am (and our machines as well) using meteor 1.4.2.3 and cordova-plugin-meteor-webapp@1.4.1.

To check if the XCode project has the flag set I am using the following search command in the generated xcode project's directory.
`find . -type f -exec grep -Hn SWIFT_VERSION {} \;`

Which returns (in my case) 3 results locally. However if I delete the build folder, run a `meteor reset` and re-build the project using `meteor build`, the find command returns 0 results instead and XCode throws an error when building from command line (obviously, since SWIFT_VERSION is not set).

I am thinking of a workaround using another plugin which allows injecting parameters in the .pbxproj, however I wanted to know if this issue was known and if there were already a workaround (that does not require you to build the project twice to populate the .meteor/codova-build folder beforehand).

Cheers

**Comment by lorensr** [comment]
I noticed having to set `SWIFT_VERSION` to 3.2 (from "unspecified") in order to fix this build error:

![image](https://user-images.githubusercontent.com/251288/33250618-99ac37e4-d2ff-11e7-8eee-b0f665fcb240.png)

**Comment by hwillson** [comment]
This has been fixed in recent versions of Meteor (>= 1.6.x).
