### ISSUE TITLE
No type or protocol named 'CDVWebViewEngineProtocol'

### ISSUE THREAD

**Issue by CyberCyclone** [meteor/cordova-plugin-meteor-webapp#3]
The attached screenshot show an error code that I receive while building for iOS.

The issue started when I upgraded to Meteor 1.3 and still exists with 1.3.1.

All the plugins are at their latest version.

The error is coming from METPlugin.h

![screen shot 2016-04-05 at 10 53 04 am](https://cloud.githubusercontent.com/assets/4373888/14268301/a5a7764c-fb1c-11e5-8d1f-2e419ab5cbda.png)

**Comment by JulianKingman** [comment]
Same issue

**Comment by clemyoh** [comment]
same issue

**Comment by hwillson** [comment]
There have been several Meteor updates since this issue was created. Please try again using a recent version of Meteor (>= 1.6.x). Thanks!
