### ISSUE TITLE
No tag for v1.4.2

### ISSUE THREAD

**Issue by lpender** [meteor/cordova-plugin-meteor-webapp#32]
Minor issue but just wanted to mention:

Release v1.4.2 doesn't seem to have been tagged and uploaded.

Thanks!
-Lee

**Comment by lpender** [comment]
Just got this as well:

```
  While adding plugin cordove-plugin-meteor-webapp@1.4.2 to Cordova project:                                       │ 4 files changed, 64 insertions(+), 58 deletions(-)
   Cordova error: Failed to fetch plugin cordove-plugin-meteor-webapp@1.4.2 via registry.
```

Thanks

**Comment by abernix** [comment]
There's a typo in the name of the package that you're trying to install:

    cordove-plugin-meteor-webapp@1.4.2
          ^ should be an 'a'

It can be verified that it was tagged and uploaded properly using the following command:

    meteor npm view cordova-plugin-meteor-webapp@1.4.2

...which will output all the pertinent details about the package and when it was uploaded.

Just in case you were talking about the [Git tag](https://github.com/meteor/cordova-plugin-meteor-webapp/tags), I've gone ahead and added that – though that's not where the plugin is installed from unless you're using the full Git URL to install it, and you can see that we haven't done that for many releases in the past.  I'll try to make sure we get better at that, but I'll certainly make sure it's published to `npm` every time. 😄
