### ISSUE TITLE
Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service

### ISSUE THREAD

**Issue by sferoze** [meteor/cordova-plugin-meteor-webapp#34]
For some reason, I cannot get the app to run on iOS..

I have tried many things.... all with different kinds of errors..

here is where I am now...

im running METEOR@1.6-rc.3 ... older versions stopped working for me :/

This version uses Cordova 7 which now does not need cordova-plugin-console...

But for some reason Meteor keeps adding this plugin to my project. 

So after I build I have to manually remove it

After removing CDVLogger plugin files the app builds

But it does not load the webview at all.... instead I just get the error

`Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service`

Here are my cordova plugins

```
cordova.define('cordova/plugin_list', function(require, exports, module) {
module.exports = [
  {
    "id": "cordova-plugin-splashscreen.SplashScreen",
    "file": "plugins/cordova-plugin-splashscreen/www/splashscreen.js",
    "pluginId": "cordova-plugin-splashscreen",
    "clobbers": [
      "navigator.splashscreen"
    ]
  },
  {
    "id": "cordova-plugin-statusbar.statusbar",
    "file": "plugins/cordova-plugin-statusbar/www/statusbar.js",
    "pluginId": "cordova-plugin-statusbar",
    "clobbers": [
      "window.StatusBar"
    ]
  },
  {
    "id": "cordova-plugin-inappbrowser.inappbrowser",
    "file": "plugins/cordova-plugin-inappbrowser/www/inappbrowser.js",
    "pluginId": "cordova-plugin-inappbrowser",
    "clobbers": [
      "cordova.InAppBrowser.open",
      "window.open"
    ]
  },
  {
    "id": "cordova-plugin-camera.Camera",
    "file": "plugins/cordova-plugin-camera/www/CameraConstants.js",
    "pluginId": "cordova-plugin-camera",
    "clobbers": [
      "Camera"
    ]
  },
  {
    "id": "cordova-plugin-camera.CameraPopoverOptions",
    "file": "plugins/cordova-plugin-camera/www/CameraPopoverOptions.js",
    "pluginId": "cordova-plugin-camera",
    "clobbers": [
      "CameraPopoverOptions"
    ]
  },
  {
    "id": "cordova-plugin-camera.camera",
    "file": "plugins/cordova-plugin-camera/www/Camera.js",
    "pluginId": "cordova-plugin-camera",
    "clobbers": [
      "navigator.camera"
    ]
  },
  {
    "id": "cordova-plugin-camera.CameraPopoverHandle",
    "file": "plugins/cordova-plugin-camera/www/ios/CameraPopoverHandle.js",
    "pluginId": "cordova-plugin-camera",
    "clobbers": [
      "CameraPopoverHandle"
    ]
  },
  {
    "id": "cordova-plugin-wkwebview-engine.ios-wkwebview-exec",
    "file": "plugins/cordova-plugin-wkwebview-engine/src/www/ios/ios-wkwebview-exec.js",
    "pluginId": "cordova-plugin-wkwebview-engine",
    "clobbers": [
      "cordova.exec"
    ]
  },
  {
    "id": "cordova-plugin-meteor-webapp.WebAppLocalServer",
    "file": "plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js",
    "pluginId": "cordova-plugin-meteor-webapp",
    "merges": [
      "WebAppLocalServer"
    ]
  },
  {
    "id": "cordova-plugin-googleplus.GooglePlus",
    "file": "plugins/cordova-plugin-googleplus/www/GooglePlus.js",
    "pluginId": "cordova-plugin-googleplus",
    "clobbers": [
      "window.plugins.googleplus"
    ]
  },
  {
    "id": "cordova-plugin-device.device",
    "file": "plugins/cordova-plugin-device/www/device.js",
    "pluginId": "cordova-plugin-device",
    "clobbers": [
      "device"
    ]
  },
  {
    "id": "cordova-plugin-keyboard.keyboard",
    "file": "plugins/cordova-plugin-keyboard/www/keyboard.js",
    "pluginId": "cordova-plugin-keyboard",
    "clobbers": [
      "window.Keyboard"
    ]
  },
  {
    "id": "cordova-plugin-launchscreen-storyboard.launchscreen",
    "file": "plugins/cordova-plugin-launchscreen-storyboard/www/launchscreen.js",
    "pluginId": "cordova-plugin-launchscreen-storyboard",
    "clobbers": [
      "window.LaunchScreen"
    ]
  }
];
module.exports.metadata = 
// TOP OF METADATA
{
  "cordova-plugin-splashscreen": "4.0.3",
  "cordova-plugin-statusbar": "2.2.3",
  "cordova-plugin-inappbrowser": "1.7.1",
  "cordova-plugin-compat": "1.2.0",
  "cordova-plugin-camera": "2.4.1",
  "cordova-plugin-whitelist": "1.3.2",
  "cordova-plugin-wkwebview-engine": "1.1.3",
  "cordova-plugin-meteor-webapp": "1.4.0",
  "cordova-plugin-googleplus": "5.1.1",
  "cordova-plugin-device": "1.1.6",
  "cordova-plugin-keyboard": "1.1.4",
  "cordova-plugin-launchscreen-storyboard": "1.0.1"
};
// BOTTOM OF METADATA
});
```

It says it is using `cordova-plugin-meteor-webapp: 1.4.0` 

But in my plugins file I defined version 1.4.2, but it wont install 1.4.2... even after clearing everything (old build folders), restarting, etc

I have also tried without `cordova-plugin-wkwebview-engine` plugin. I never used it originally but just added it in an attempt to get the app to build.

I have no idea how to proceed. I cannot build my app for iOS anymore, and I have been working the whole day trying to build it. I am stuck. Please help.

**Comment by RileyDavidson-Evans** [comment]
Are you still experiencing this issue ? I'm still getting the error and white screen

**Comment by compelling** [comment]
think this is related to the wkwebview plugin - i'm getting a white screen and the  "Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service"  log in another application when just adding this plugin

**Comment by RileyDavidson-Evans** [comment]
@sferoze Have you found a solution to this?

**Comment by compelling** [comment]
I solved the issue in the other application by adding this plugin https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix  mentioned in this post  https://stackoverflow.com/questions/33211442/wkwebview-cannot-trigger-ajax-to-load-a-file-on-local

**Comment by Drewster727** [comment]
@compelling thank you, that fixed my issue! I was running into the same problem.

**Comment by RileyDavidson-Evans** [comment]
@Drewster727 I've installed the package using `meteor add cordova:cordova-plugin-wkwebviewxhrfix@https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix.git#593eb98a155bd1f970276222be8c6bfa757568f4` and I'm still getting this error ! Any thing you did in particular ?

**Comment by Drewster727** [comment]
@RileyDavidson-Evans  sorry I'm not actually using meteor. I found this thread in a search and had an issue where my splash was hanging with wkwebview. compelling's suggestion fixed it for me. All I did was add the plugin.

**Comment by sferoze** [comment]
@RileyDavidson-Evans The application not loading was due to another error. 

I am still getting `Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service` error but the application works just fine. I am not sure about this error, but I am ignoring it for now, since everything seems to be working a ok

**Comment by RileyDavidson-Evans** [comment]
@sferoze what version of xcode / ios are you working with ?

**Comment by jamauro** [comment]
Also seeing this issue on a fresh project using https://github.com/meteor/simple-todos-svelte. Tried adding this plugin https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix to no avail. Does anyone know how to resolve?

**Comment by Maudini** [comment]
Plus one on this. Dealing with 
```
com.apple.WebKit.WebContent: 113: Could not find specified service
com.apple.WebKit.Networking: 113: Could not find specified service
```
I've been reading that this was[ supposed to have been dealt with](https://forums.meteor.com/t/meteor-1-3-beta-modules-mobile-and-testing-now-available/18186) in **Meteor version 1.3**, so not sure why this issue would still be coming up?

**Comment by filipenevola** [comment]
Hi, could you provide a reproduction using latest Meteor? 😉 Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

**Comment by Maudini** [comment]
Ended up I just needed to `rm -rf .meteor/local/cordova-build    `

**Comment by filipenevola** [comment]
Ok, as we don't have a reproduction I'm going to close this issue. If someone is still facing it please open a new issue.
