### ISSUE TITLE
Android: Incorrect version of index document loaded on HCP

### ISSUE THREAD

**Issue by denisbabineau** [meteor/cordova-plugin-meteor-webapp#4]
On reload from HCP, the index document loaded is of the previous version/bundle while other scripts/assets are loaded from the new version/bundle. This can be observed by inspecting **meteor_runtime_config**.autoupdateVersionCordova which remains the same until the app is restarted (or a browser refresh is forced from chrome inspector). 

Adding breakpoints in native code I was able to confirm that remapUri() for the document request was invoked before the call to onReset() on WebAppLocalServer causing the document to be served from the previous bundle.

This appears to be a race condition between the web engine and the main thread as I've seen some cases where onReset() was called first. I've also seen multiple requests go thru before onReset() when putting a breakpoint in onReset().

Can be reproduced with blank project using Meteor 1.3.2.3. This does not occur with iOS.

**Comment by hwillson** [comment]
There have been several Meteor updates since this issue was created. Please try again using a recent version of Meteor (>= 1.6.x). Thanks!
