### ISSUE TITLE
Pull requests: GCDWebServer & HCP

### ISSUE THREAD

**Issue by KoenLav** [meteor/cordova-plugin-meteor-webapp#43]
I opened some pull requests in an effort to get some discussion started around updating GCDWebServer and applying some of the proposed fixes to the HCP mechanism.

@abernix I think it would be nice to invest some time in this as these issues are probably hitting many developers, of which most are not aware that these issues even exist (simply asking their users to restart/reinstall the application).

With Meteor 1.6 you have reached a new level of stability, in terms of server and client, I think the Cordova implementation should be able to perform likewise.

**Comment by macrozone** [comment]
because of the bugs i and others used my branch https://github.com/meteor/cordova-plugin-meteor-webapp/pull/30, but 1.6.1. seems to break that version. It's a shame, that these problems get no attention from mdg. 

I tried to help @KoenLav with the PR, but its just horror. I barely know swift and how the meteor integration should work. We really need the help of experts here.

**Comment by macrozone** [comment]
as a work-around i changed manifest-url in my old PR https://github.com/meteor/cordova-plugin-meteor-webapp/pull/30 to use the new path (__meteor__/webapp/)

in the pr https://github.com/meteor/cordova-plugin-meteor-webapp/pull/30 you see instruction how to install it

**Comment by paulincai** [comment]
Hi,

I see with https://github.com/bmanturner/cordova-plugin-meteor-webapp that there is some type of handling of new bundle versions.

`Reload._onMigrate(function (retry) {
  if (Meteor.isCordova) {
    cordova.exec(callback, console.error, 'WebAppLocalServer', 'switchPendingVersion', []);
  }
  return [true, {}];
});`

Are these following packages redundant in the context of the new cordova-plugin-meteor-webapp?

jamielob:reloader or mdg:reload-on-resume 

Tx,
Paul

**Comment by macrozone** [comment]
@paulincai i don't know jamielob:reloader, but mdg:reload-on-resume has a different purpose and is unaffected by this issue here.
