### ISSUE TITLE
Xcode Build Error

### ISSUE THREAD

**Issue by xpluscal** [meteor/cordova-plugin-meteor-webapp#5]
When trying to compile an iOS-App, I currently get a Build Failure due to this plugin.

Any help appreciated.

<img width="249" alt="screen shot 2016-04-26 at 13 49 20" src="https://cloud.githubusercontent.com/assets/3706722/14817177/b5c9f938-0bb5-11e6-90ae-a442eb6f9373.png">

**Comment by octohedron** [comment]
Anyone knows how to solve this on Xcode 8?

**Comment by johnthepink** [comment]
@xpluscal @octohedron have you tried this? https://forums.meteor.com/t/ios-10-compatibility/26065/16

**Comment by hwillson** [comment]
This issue has been fixed in more recent versions of Meteor - thanks!
