### ISSUE TITLE
Fail on Android

### ISSUE THREAD

**Issue by jwall149** [meteor/cordova-plugin-meteor-webapp#7]
In my application, i intercept the `onNewVersionReady` callback to notify user an update message with an OK button. If user click OK, I call the `location.reload()`. 

As my understand it works like this:
1. Cordova notifies that new version is ready, and create a `pendingAssetBundle`.
2. Somewhere in the webview, `location.reload()` is called.
3. Cordova plugins call `onReset()`, the `currentAssetBundle` (old assets) is switched to `pendingAssetBundle` (new assets).
4. Webview serving new assets as normal

But for our real experiment, 90% of the time it ends up with:
1. Cordova notifies that new version is ready, and create a `pendingAssetBundle`.
2. Somewhere in the webview, `location.reload()` is called.
3. Cordova server `index.html` and some others of old assets (`currentAssetBundle`).
4. Cordova plugins call `onReset()`, the `currentAssetBundle` (old assets) is switched to `pendingAssetBundle` (new assets).
5. Webview serving new assets

This make the errors that index.html contained outdated minified js/css doesn't exists in new bundle, and new version got rollbacked every time.

So we end with a solution that exposing a function `switchAssetBundle` that switches asset bundles (current and pending). On callback of that function, we perform `location.reload()` and thats work.

**Comment by levinse** [comment]
Is this similar to https://github.com/meteor/meteor/issues/8063?

**Comment by lorensr** [comment]
@jwall149 I'd like to try your `switchAssetBundle` function to fix my app – it would be a great help if you could share that code and show where the function is called from?

**Comment by hwillson** [comment]
Is this issue still happening using a recent version of Meteor? If so, could anyone here provide a small runnable reproduction that shows this happening?

**Comment by benjamn** [comment]
Please feel free to reopen this issue if the problem is still happening in Meteor 1.8.
