### ISSUE TITLE
cannot build with 1.6.3+

### ISSUE THREAD

**Issue by wildhart** [meteor/cordova-plugin-meteor-webapp#74]
In attempting to upgrade from 1.8.0.2 to 1.8.1-beta-16 my android build no longer compiles.

I've removed all my cordova plugins and tracked it down to cordova-plugin-meteor-webapp 1.6.3+

Using any previous version builds OK (but crashes immediately on install because no plugins), but starting with 1.6.3 up to yesterday's 1.6.5 I get the following build error:
```js 
                                              
   While running Cordova app for platform Android with options --buildConfig,/home/chris/inout/.meteor/local/cordova-build/build.json,--device:
   Error: Command failed: /home/chris/inout/.meteor/local/cordova-build/platforms/android/cordova/run --buildConfig /home/chris/inout/.meteor/local/cordova-build/build.json --device
   FAILURE: Build failed with an exception.
   
   * Where:
   Script '/home/chris/inout/.meteor/local/cordova-build/platforms/android/cordova-plugin-meteor-webapp/app-build-extras.gradle' line: 24
   
   * What went wrong:
   A problem occurred evaluating project ':app'.
   > Cannot add task ':app:cdvCreateAssetManifest' as a task with that name already exists.
```
Downgrading to 1.6.2 builds, upgrading to 1.6.3 doesn't.

I'm on Linux Mint.  `gradle` command line gives v 4.10.2 (whether or not that's the version meteor is using I'm not sure).

**Comment by Nauzer** [comment]
Can you post your cordova plugin list and a --verbose version of the build output?
I had to adjust the plugin.xml of one plugin to prevent duplicate entries in AndroidManifest.xml to prevent and error I think was similar.

Long shot: did you try to do rm -rf .meteor/local/cordova-build && meteor remove-platform android && meteor add-platform android before running?

**Comment by wildhart** [comment]
Thanks @Nauzer, `rm -rf .meteor/local/cordova-build && meteor remove-platform android && meteor add-platform android` managed to get it working, although I did do regular `meteor reset` and `meteor remove/add-platform android`.
