### ISSUE TITLE
[Android] Error: Could not create download directory for large files in public directory

### ISSUE THREAD

**Issue by brucejo75** [meteor/cordova-plugin-meteor-webapp#81]
I started seeing this error recently with Meteor **v1.8.1**.
I also upgraded / added `cordova-background-geolocation-lt@3.0.0` at this point.

Note: I am still investigating to make sure my app is not causing this...
Thought I would get the issue entered, on the hope that someone else had this happen.

### Environment
Meteor: **v1.8.1**
Android: **v8.1.0**
Cordova: **7.1.4**

plugins:
- cordova-background-geolocation-lt@**3.0.0**
- cordova-plugin-app-version@**0.1.9**
- cordova-plugin-cartegraph-cookie-master@**1.3.0**
- cordova-plugin-customconfigparameters@**3.0.0**
- cordova-plugin-device@**2.0.2**
- cordova-plugin-device-name@**1.3.4**
- cordova-plugin-statusbar@**2.4.2**

### Repro
1. Create app with meteor build
2. Deploy app on Android device and run it.

**Result:**
```bash
Error: Could not create download directory
    at :12848/plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js:51
    at Object.callbackFromNative (cordova.js:291)
    at <anonymous>:1:9
(anonymous) @ webapp.js:37
webapp.js:37 Error: timeout
    at :12848/plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js:51
    at Object.callbackFromNative (cordova.js:291)
    at <anonymous>:1:9
(anonymous) @ webapp.js:37
```

Initial HCP appears to not work.  The app seems to work fine.

### Workaround
It seems that shutting down the app and restarting will stop displaying the error and HCP works again.

**Comment by brucejo75** [comment]
Another observation, my workaround is a little more complicated.

**Workaround:** While the app is running and connected to the server, update the server with new client code.

If I:
1. shutdown the app
2. update the server app with new client code.
3. restart the app

**Result:** code does not update on the client app.

Going to try testing with a full build, instead of a dev run.

**Comment by Nauzer** [comment]
Do I understand it correctly that this issue is occurring for you on local development?
Would be good to know if you can reproduce it with a PROD built server and client connecting to that as well.

**Comment by brucejo75** [comment]
I also see the issue with a `debug` build running on my production server.  I have not built a production version.

I have not had time to investigate further and I am building a workaround for my product that seems to work well enough.

After I get this next release out, I will try to isolate the issue more.  I am suspicious of `ordova-background-geolocation-lt@3.0.0` as that is the newest plugin I am using.

**Comment by Nauzer** [comment]
@brucejo75 Do I understand you right that you've made changes to your Cordova plugins on the server after the moment you initially built? If so the behaviour can be explained as HCP does not work when changes to your Cordova plugins are made. Don't think there is a workaround for that.

https://guide.meteor.com/mobile.html#updating-production-apps

**Comment by brucejo75** [comment]
I am aware that changing the cordova plugins requires a rebuild of the client side app (or manipulation of the compatibility version).

To be clear - No, I am not changing the plugins between builds.

My workaround is to see if the client side app version is the same as the build version of the app.  If they are the same I know that the latest client has not been HCP'ed to my app.  So I wait 60 seconds and the do a `location.reload`.  After 2-4 reloads, HCP completes.  That seems to be working for me for now, until I can dig into it further.

**Comment by brucejo75** [comment]
D'oh.  I figured out the issue

I had a number of `.apk`s sitting in my public directory.  So Meteor was timing out downloading the `.apk`s.

Moral of the story?  Keep your public directory clean.  Or at least minimized.

I would recommend that instead of outputting: `Could not create download directory` it might be better to display the size of the downloads that Meteor is dealing with.  And then warn the user that the size should be minimized for a number of good reasons.

**Comment by brucejo75** [comment]
Fixed by cleaning out public directory.
