### ISSUE TITLE
Asset /cordova.js not found in bundle

### ISSUE THREAD

**Issue by heikkipviidakko** [meteor/cordova-plugin-meteor-webapp#85]
After updating to Meteor 1.8.1 with cordova-plugin-meteor-webapp version 1.7.0 I'm getting console logs that say that cordova items are not found in the bundle:

10-07 10:37:33.095  7347  7406 W MeteorWebApp: Asset /cordova.js not found in bundle 27625ccbf1d2ecae14073bd023729365bbf7d3fc:file:///android_asset/www/application, no parent bundle
10-07 10:37:33.444  7347  7405 W MeteorWebApp: Asset /cordova_plugins.js not found in bundle 27625ccbf1d2ecae14073bd023729365bbf7d3fc:file:///android_asset/www/application, no parent bundle
10-07 10:37:33.458  7347  7405 W MeteorWebApp: Asset /plugins/cordova-plugin-meteor-webapp/www/webapp_local_server.js not found in bundle 27625ccbf1d2ecae14073bd023729365bbf7d3fc:file:///android_asset/www/application, no parent bundle
10-07 10:37:33.460  7347  7405 W MeteorWebApp: Asset /plugins/cordova-plugin-statusbar/www/statusbar.js not found in bundle 27625ccbf1d2ecae14073bd023729365bbf7d3fc:file:///android_asset/www/application, no parent bundle
10-07 10:37:33.473  7347  7405 W MeteorWebApp: Asset /plugins/cordova-plugin-splashscreen/www/splashscreen.js not found in bundle 27625ccbf1d2ecae14073bd023729365bbf7d3fc:file:///android_asset/www/application, no parent bundle

Meteor version: 1.8.1
Platform: Android

The app seems to be working correctly. The same happens if I create a new empty meteor project, add android platform and run the project on an Android device. Is this something that is expected or is there possibly something wrong with my setup?

**Comment by Ruben-dai** [comment]
@heikkipviidakko, did you find any solution?  Same problem here....

**Comment by heikkipviidakko** [comment]
No, I didn't find a solution. The app works correctly despite of the confusing logs.

**Comment by CristianoGil** [comment]
I have same problem with Meteor 1.9,  webapp.1.8.2

**Comment by filipenevola** [comment]
If you are still seeing this on 1.10.1 please re-open.

**Comment by CristianoGil** [comment]
+1

**Comment by jmark1m** [comment]
+1

**Comment by p13rnd** [comment]
+1

**Comment by filipenevola** [comment]
Hi @p13rnd can you open another issue with a reproduction? I don't see this problem on my apps.

Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)
