### ISSUE TITLE
IOS - Local Web server Crashes

### ISSUE THREAD

**Issue by Wade-BuildOtto** [meteor/cordova-plugin-meteor-webapp#90]
At random, when users open the app the local web server has crashed, images are missing, nothing is able to load anymore. With what was still loaded it is still able to make method calls to change the data. 

I had it timeout after if the user didn't return to the app within 5 min to do a window.location.reload() but if the web server had crashed this wouldn't execute. 

with 1.7.1 and below I was using https://github.com/panter/cordova-plugin-meteor-webapp.git#7bb095ce393d17f662cc6bb596ce91acf743d17a which reduced it a lot, once I moved up to 1.8.1 I removed this and its seems to be back, though not as bad as it was before. 

I have seen other people with the same issue who are also using cordova-background-geolocation, the also dies in the background after 2-3 days no crash report no errors just gone.

https://forums.meteor.com/t/cordova-local-webserver-dies-on-ios-after-some-time-in-the-background/36694
and 
https://github.com/meteor/cordova-plugin-meteor-webapp/issues/27

I am using the transistorsoft version: https://github.com/transistorsoft/cordova-background-geolocation
but also https://github.com/mauron85/cordova-plugin-background-geolocation#readme

This has been an ongoing issue for years since 1.3.5 I was hoping the latest version would address it, will try 1.8.3 next but I don't think there are any changes in this area.

**Comment by filipenevola** [comment]
Hi, we are updating Cordova to 9 (latest) in Meteor 1.10 (https://github.com/meteor/meteor/pull/10861) and we already have a beta version for it, could you try your app in 1.10-beta.2 and let us know if this issue is fixed?

Make sure all your plugins are also up-to-date.

**Comment by StorytellerCZ** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
