### ISSUE TITLE
Failed to install 'cordova-plugin-meteor-webapp': Using "requireCordovaModule" to load non-cordova module "fs" is not supported.

### ISSUE THREAD

**Issue by myoneflag** [meteor/cordova-plugin-meteor-webapp#97]
Updated meteor mobile app from METEOR@1.8.1-issue-10516.0  to METEOR@1.11.1
ExitWithCode { code: 1 } when meteor run ios-device

=> Started MongoDB.                           
%% Failed to install 'cordova-plugin-meteor-webapp': Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/Users/macbook/.meteor/packages/meteor-tool/.1.11.1.12ablfz.sn6d++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/macbook/Desktop/Factbox/CommitSwimming/CommitSwimming/workouts/workouts-mobile/.meteor/local/cordova-build/plugins/cordova-plugin-meteor-webapp/scripts/iosAddBridgingHeader.js:2:20)
    at runScriptViaModuleLoader (/Users/macbook/.meteor/packages/meteor-tool/.1.11.1.12ablfz.sn6d++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/Users/macbook/.meteor/packages/meteor-tool/.1.11.1.12ablfz.sn6d++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /Users/macbook/.meteor/packages/meteor-tool/.1.11.1.12ablfz.sn6d++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at /Users/macbook/.meteor/packages/meteor-tool/.1.11.1.12ablfz.sn6d++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/fiber_pool.js:43:40
=> Errors executing Cordova commands:                                           
                                                                                
   While adding plugin cordova-plugin-meteor-webapp@1.7.0 to Cordova project:   
   Cordova error: Using "requireCordovaModule" to load non-cordova module "fs"  
   is not supported. Instead, add this module to your dependencies and use
   regular "require" to load it.
   (If the error message contains suggestions for a fix, note that this may not 
   apply to the Meteor integration. You can try running again with the
   --verbose option to help diagnose the issue.)
                                                                                
/Users/macbook/.meteor/packages/coffeescript/.1.0.17.13vgf3h.8siw++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
      ^
ExitWithCode { code: 1 }

Thank you

**Comment by jnurkka** [comment]
Having the same issue/similar issue after updating to meteor 1.11. (also the first time building with Xcode 14, maybe that could also be an issue?):

```
While preparing Cordova project for platform iOS:
   Cordova error: Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
   (If the error message contains suggestions for a fix, note that this may not apply to the Meteor integration. You can try running again with the --verbose option to help diagnose the issue.)
```

Running with `--verbose` isn't providing any useful outputs, unfortunately.

```
Xcode version: 12.0.1
Meteor: 1.11.1
cordova-plugin-meteor-webapp: 1.9.1
```

**Comment by myoneflag** [comment]
firstly try please
`meteor remove-platform ios`
`meteor add-platform ios`

**Comment by jnurkka** [comment]
> firstly try please
> `meteor remove-platform ios`
> `meteor add-platform ios`

@myoneflag This didn't work for me (see my comment above), but I managed to fix this issue by completely removing my local meteor installation (on Mac you can find it in `/Users/youruser/.meteor/` folder) and then installing meteor again. After that the build succeeded.
