### ISSUE TITLE
Meteor Cordova ProjectBuild.js Dependancies missing "cordova-common", "compare-func"

### ISSUE THREAD

**Issue by Wade-BuildOtto** [meteor/cordova-plugin-meteor-webapp#98]
i have been having a build issue since meteor 1.9, 1.10, and 1.11 and only after a dig into the build project did I locate the issue, 

some how I didn't have cordova-common or compare-func pre-installed on my system which gave the issue they were missing, which if they are used should have a package dependancy

%% Updating build files since android plugin contained <framework>
%% Failed to install 'cordova-plugin-meteor-webapp': Error: Cannot find module 'cordova-common' 

**.meteor/local/platforms/android/cordova/lib/builders/ProjectBuilder.js**
```
  var spawn = require('cordova-common').superspawn.spawn;
  var events = require('cordova-common').events;
  var CordovaError = require('cordova-common').CordovaError;
  ...
  const compareFunc = require('compare-func');
```

once npm installed the my project started to build again.

**Comment by filipenevola** [comment]
Hi, could you provide a reproduction? 😉 Read more [here](https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md#reporting-a-bug-in-meteor)

**Comment by Wade-BuildOtto** [comment]
once I manually installed those packages, that issue cleared. but when I rebuilt the node_modules folder, they still didn't install so they seemingly are not dependancies that I can find, but are used in the build process.

**Comment by filipenevola** [comment]
Hi @Wade-BuildOtto, we need more information to be able to understand the issue. I have a few Meteor apps in production with Cordova and I never saw this issue before.

Can you provide a production as explained here https://github.com/meteor/meteor/blob/devel/CONTRIBUTING.md?rgh-link-date=2020-11-10T16%3A38%3A44Z#reporting-a-bug-in-meteor?

**Comment by StorytellerCZ** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
